Redefine QEMU_TARGETS list for mx8 to remove riscv32 riscv64
The qemu-qoriq recipe does not support building riscv architectures,
solves below error:

-- snip --
ERROR: Unknown target name 'riscv32-linux-user'
-- snip --

Signed-off-by: Jagadeesh Krishnanjanappa <jkrishnanjanappa@mvista.com>