Prefer using mesa to provide virtual/egl if LICENSE_FLAGS_WHITELIST is not set to xilinx
Solves below error:
-- snip --
ERROR: Nothing PROVIDES 'virtual/egl' (but .../layers/poky/meta/recipes-graphics/mesa/mesa-demos_8.3.0.bb, .../layers/poky/meta/recipes-graphics/libepoxy/libepoxy_1.5.2.bb, .../layers/poky/meta/recipes-multimedia/gstreamer/gstreamer1.0-plugins-base_1.14.4.bb DEPENDS on or otherwise requires it)
mesa PROVIDES virtual/egl but was skipped: PREFERRED_PROVIDER_virtual/libgl set to mesa-gl, not mesa
libmali-xlnx PROVIDES virtual/egl but was skipped: because it has a restricted license not whitelisted in LICENSE_FLAGS_WHITELIST
NOTE: Runtime target 'mesa-demos' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['mesa-demos', 'virtual/egl']
NOTE: Runtime target 'packagegroup-core-tools-testapps' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-core-tools-testapps', 'mesa-demos', 'virtual/egl']
NOTE: Runtime target 'packagegroup-profile-cgl' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-profile-cgl', 'packagegroup-core-tools-testapps', 'mesa-demos', 'virtual/egl']
ERROR: Required build target 'cgx-complete-image' has no buildable providers.
Missing or unbuildable dependency chain was: ['cgx-complete-image', 'packagegroup-profile-cgl', 'packagegroup-core-tools-testapps', 'mesa-demos', 'virtual/egl']
-- snip --

Signed-off-by: Jagadeesh Krishnanjanappa <jkrishnanjanappa@mvista.com>